# Generated by Django 5.0 on 2024-01-01 15:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinputmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_type', models.CharField(max_length=100)),
                ('availiability', models.DateField(max_length=10)),
                ('Total_sqft', models.IntegerField()),
                ('Bhk', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('phone_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
